### ISSUE TITLE
PIN and path switches collide

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#119]
For Nitrokey 3 test command `-p` switch means `--pin` and collides with parent's `--path` switch.

```
$ nitropy nk3 test -p /dev/hidraw4
Nitrokey tool for Nitrokey FIDO2, Nitrokey Start, Nitrokey 3 & NetHSM
Found 1 Nitrokey 3 device(s):
- Nitrokey 3 at /dev/hidraw6

Running tests for Nitrokey 3 at /dev/hidraw6

```

**Comment by robin-nitrokey** [comment]
It’s probably best to just remove the shorthand for `--pin` because it is already quite short.  Note that the position of these two flags is relevant here:  The `--path` option is for the `nk3` command group, so it has to come before the subcommand.  The `--pin` option is for the `test` subcommand, so it has to come after it.
```
$ nitropy nk3 test -p /dev/hidraw4
Nitrokey tool for Nitrokey FIDO2, Nitrokey Start, Nitrokey 3 & NetHSM
Found 1 Nitrokey 3 device(s):
- Nitrokey 3 at /dev/hidraw3

Running tests for Nitrokey 3 at /dev/hidraw3
```
```
$ nitropy nk3 -p /dev/hidraw4 test
Nitrokey tool for Nitrokey FIDO2, Nitrokey Start, Nitrokey 3 & NetHSM
Critical error:
No connected Nitrokey 3 devices found
```
As far as I know, there is no easy way to make the `nk3` `--path` option global so that it is also accepted after the `test` subcommand.

**Comment by szszszsz** [comment]
1. Agreed, `--pin` is sufficient. 
2. About the global switch, that's not intuitive at all :eyes:
