### ISSUE TITLE
Nitrokey3 secrets not listable

### ISSUE THREAD

**Issue by kizm0** [Nitrokey/pynitrokey#354]
Hello i am using following command:
`nitropy nk3 secrets list`

and get the following error message:
_please touch the device if it blinks
Authentication failed with error: "CTAP error: 0x01 - INVALID_COMMAND"
Aborted!_

the devices is not blinking, in the error log i only get errors from different devices not from the nitrokey /dev/hidrawx...

system information:
Nitrokey 3 - firmware 1.2.2
357        INFO pynitrokey.cli Python version: 3.10.6
360        INFO pynitrokey.cli pynitrokey version: 0.4.34
361        INFO pynitrokey.cli cryptography version: 36.0.2
362        INFO pynitrokey.cli ecdsa version: 0.18.0
362        INFO pynitrokey.cli fido2 version: 1.1.0
363        INFO pynitrokey.cli nrfutil version: 6.1.7
379        INFO pynitrokey.cli pyusb version: 1.2.1
380        INFO pynitrokey.cli spsdk version: 1.7.1

**Comment by szszszsz** [comment]
Hello!

Secrets are so far available only in the unstable firmware (since `v1.2.2-alpha.20230224`), but that should change soon - see release candidate.  You can update device to the latter and use it already for tests, however for the actual production use I recommend to wait for the stable release.

See here for more details:
- https://github.com/Nitrokey/nitrokey-3-firmware/releases/tag/v1.3.0-rc.1
- https://github.com/Nitrokey/nitrokey-3-firmware/releases (all releases)
